# -*- coding: utf-8 -*-
"""A FELHASZNÁLÓ SAJÁT NEVEI — védett, utolsó réteg (3.9.217)

KIMONDOTT KÉRÉS (2026-10-06): „Olyan neveket nem kéne javasolj amik általam
lettek átírva. Volt egy régi commit Danisítás néven, és a körül egy jó párat
én írtam még át, még előtte is. Azokat figyelembe kéne venni."

MI VAN ITT
  SAJAT_KULCSOK — minden név, amit a felhasználó maga írt át, a forrásával.
      Ezekre JAVASLAT NEM KÉSZÜLHET (lásd javaslat_ellenor.py).
  SAJAT         — a befagyasztott értékek. A build.py a MANUAL betöltése UTÁN,
      UTOLSÓKÉNT húzza rá a táblára: sem a szabálymotor, sem egy későbbi
      javaslatkör (JAVASLAT_*) nem írhatja felül. Ha valami mégis mást adna,
      a build kiírja („SAJÁT NÉV VÉDVE").
  DONTESRE_VAR  — a felhasználó saját neve, amit egy KORÁBBI, jóváhagyott
      javaslatkör már felülírt. Itt nincs befagyasztva (a mostani alak él),
      de kulcsként védett — a visszaállítás a felhasználó döntése.

A FORRÁSOK (a teljes git-történetből kigyűjtve, nem emlékezetből)
  · bf84bde „Nevek Danisítása lvl100" (mistral757, 2026-09-01) — 240 név;
    a b772dd8 (3.9.07) mentette át a manual.py-ba;
  · a 29–32. köteg danisítása (3.9.81–3.9.84) — a felhasználó kézi átiratai;
  · a 3.9.87-es kör, a 33., a 35. és a 36. köteg — a felhasználó kézbe vett
    nevei;
  · a 2026-10-06-i kérés: hét név, és Ziyech + Kolo Touré.

HOGYAN BŐVÜL: ha a felhasználó új nevet ír át (vagy visszaállít egyet a
DONTESRE_VAR-ból), az ide kerül — nem a manual.py valamelyik JAVASLAT
blokkjába.
"""

SAJAT_KULCSOK = {
  "Aaron Lennon": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Adamo Coulibaly": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ademola Lookman": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Adriano": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Adrien Rabiot": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Adrián": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Adílson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alan Shearer": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alberto Gilardino": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alberto Moreno": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Aleksandr Anyukov": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alessandro Bastoni": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alessandro Birindelli": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Alessandro Costacurta": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alessandro Nesta": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alessio Romagnoli": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alessio Tacchinardi": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Alex McLeish": "a 33. köteg (3.9.114)",
  "Alex Oxlade-Chamberlain": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alexander Isak": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alexander Sørloth": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alexandre Lacazette": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alexis Mac Allister": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alexis Saelemaekers": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alexis Sánchez": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alfredo Di Stéfano": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Alisson Becker": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Altay Bayındır": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Amir Hadžiahmetović": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Andrea Pirlo": "a felhasználó kérése (2026-10-06)",
  "Andrea Ranocchia": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Andreas Isaksson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Andrei Arshavin": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Andrij Sevcsenko": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Andriy Lunin": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "André Schürrle": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "André-Pierre Gignac": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Andrés Iniesta": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Antoni Ramallets": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Antonio Cabrini": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Antonio Di Natale": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Artem Dzyuba": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ashley Young": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Aurélien Tchouaméni": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Axel Witsel": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Batista": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Batistuta": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Bebeto": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Beckenbauer": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Benjamin Pavard": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Bergkamp": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Bernd Hölzenbein": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Bernd Schneider": "a 35. köteg (3.9.117)",
  "Blaise Matuidi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Branislav Ivanović": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Brian Laudrup": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Bruno Fernandes": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Bruno Guimarães": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Bryan Cristante": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Cantona": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Casemiro": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Charles De Ketelaere": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Chris Armstrong": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Chris Smalling": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Chris Woods": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Christian Abbiati": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Christian Fuchs": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Christian Karembeu": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Christian Schulz": "a 35. köteg (3.9.117)",
  "Ciro Immobile": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Claudio Marchisio": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Claudio Pizarro": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Clint Dempsey": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Cody Gakpo": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Coen Moulijn": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Colin Calderwood": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Corentin Tolisso": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Costinha": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Cruyff": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Dani Olmo": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Daniel Agger": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Daniel Carvalho": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Daniel Passarella": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Daniel Sturridge": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Daniel Van Buyten": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Daniele De Rossi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Danijel Subašić": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Danilo": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Danilo D'Ambrosio": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Danny": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Danny Rose": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Darren Anderton": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Darwin Núñez": "a 35. köteg (3.9.117)",
  "David Beckham": "a felhasználó kérése (2026-10-06)",
  "David Ginola": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "David Ospina": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "David Seaman": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Davide Zappacosta": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Dayot Upamecano": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Declan Rice": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Deco": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Dejan Kulusevski": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Dejan Stanković": "a 35. köteg (3.9.117)",
  "Denílson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Derlei": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Di Stéfano": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Didi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Diego": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Diego Forlán": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Diego Milito": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Diego Tristán": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Diogo Jota": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Dirk Kuyt": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Divock Origi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Djibril Cissé": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Djimi Traoré": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Dombi Tibor": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Domenico Criscito": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Dominic Calvert-Lewin": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Douglas Costa": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Dragan Stojković": "a 36. köteg (3.9.119)",
  "Dries Mertens": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Dwight Yorke": "a 33. köteg (3.9.114)",
  "Ederson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Eduardo Camavinga": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Edílson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Eliseu": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Emil Forsberg": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Emmanuel Adebayor": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Emmanuel Ntim": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Emmanuel Petit": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Emre Can": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Enrico Chiesa": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Eric Cantona": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Eric Dier": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Eric Maxim Choupo-Moting": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Erling Haaland": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Erwin Koeman": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Estanislau Basora": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Esteban Cambiasso": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Everton": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ezequiel Garay": "a 33. köteg (3.9.114)",
  "Ezequiel Lavezzi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Fabio Grosso": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Fabrizio Miccoli": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Falcão": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Federico Bernardeschi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Federico Chiesa": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Federico Valverde": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Fernando Couto": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Filippo Inzaghi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Florian Wirtz": "a 33. köteg (3.9.114)",
  "Flávio Conceição": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Franco Mastantuono": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Frank Anguissa": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Frank de Boer": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Freddie Ljungberg": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gabi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gabriel Batistuta": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gabriel Heinze": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gabriel Jesus": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gabriel Milito": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gareth Barry": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Gareth Southgate": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gavi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Georg Schwarzenbeck": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Georgi Kinkladze": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gianluca Pagliuca": "a 33. köteg (3.9.114)",
  "Gift Orban": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gilberto Silva": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Giorgi Mamardashvili": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Giovanni Reyna": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Giuseppe Signori": "a 35. köteg (3.9.117)",
  "Gonzalo Higuaín": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Granit Xhaka": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Grosics Gyula": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Grégory Coupet": "a 33. köteg (3.9.114)",
  "Gullit": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gulácsi Péter": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Gunnar Gren": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Gunnar Nordahl": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Gustau Biosca": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Guti": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Hakim Ziyech": "a felhasználó saját átirata (2026-10-06-i jelzés)",
  "Hans-Georg Schwarzenbeck": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Harald Schumacher": "a 35. köteg (3.9.117)",
  "Harry Kewell": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Helton": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Henrikh Mkhitaryan": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Hernán Crespo": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Hiroki Ito": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Hugo Ekitiké": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Hugo Lloris": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Hugo Viana": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Hulk": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Hélder Postiga": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ian Ferguson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ian Walker": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Ibrahim Afellay": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ibrahim Cissé": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ibrahima Konaté": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ibrahima Sissoko": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Idrissa Gueye": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Igor Bogdanović": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ivan Rakitić": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Iván Córdoba": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Jack Grealish": "a 35. köteg (3.9.117)",
  "Jadon Sancho": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "James Milner": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Jamie Vardy": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jan Koller": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jan Oblak": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jan Wouters": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Jefferson Farfán": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jemerson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jeremie Frimpong": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jermain Defoe": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jerzy Dudek": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Jesús Fernández": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jesús Gámez": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jesús Navas": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Joan Segarra": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Joe Gomez": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Joe Hart": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "John Arne Riise": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "John Bosman": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "John Obi Mikel": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "John van 't Schip": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Joleon Lescott": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Jordan Pickford": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jordi Cruyff": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jorginho": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Josemi": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "José Callejón": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "José Fonte": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "João Manuel Pinto": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "João Neves": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Juan Cuadrado": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Julian Brandt": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Julian Draxler": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Jérémy Mathieu": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Jürgen Grabowski": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kai Havertz": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kalidou Koulibaly": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Kamil Glik": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Kasper Schmeichel": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kerkez Milos": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Khalid Boulahrouz": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Kim Jin-su": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kim Min-jae": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kingsley Coman": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kolo Touré": "a felhasználó saját átirata (2026-10-06-i jelzés)",
  "Kostas Manolas": "a 35. köteg (3.9.117)",
  "Kostas Tsimikas": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Kubala László": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Kwoun Sun-tae": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Kylian Mbappé": "a felhasználó kérése (2026-10-06)",
  "Leandro Paredes": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Leandro Trossard": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Lee Kang-in": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Leon Goretzka": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Leonardo Spinazzola": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Lionel Scaloni": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Lisandro Martínez": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Lorenzo Insigne": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Lorenzo Pellegrini": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Lucas Hernández": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Luka Jović": "a 35. köteg (3.9.117)",
  "Lukas Podolski": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Manuel Akanji": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Manuel Locatelli": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marc Cucurella": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marc Overmars": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marc-André ter Stegen": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marcel Tisserand": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Marcelo Salas": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marco Asensio": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marco Materazzi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marco Reus": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marcos Senna": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Marek Hamšík": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Mario Balotelli": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Mario Corso": "a 33. köteg (3.9.114)",
  "Mario Kempes": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Mark Hughes": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Mark Iuliano": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Mark van Bommel": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Martin Peters": "a 35. köteg (3.9.117)",
  "Martin Škrtel": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Martín Demichelis": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Mathieu Debuchy": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Mauro Camoranesi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Micah Richards": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Michael Owen": "a felhasználó kérése (2026-10-06)",
  "Milan Baroš": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Milan Škriniar": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Mimis Domazos": "a 35. köteg (3.9.117)",
  "Moisés Caicedo": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Mário Jardel": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nani": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Nathan Aké": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Nazım Sangaré": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Neven Subotić": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Nicola Amoruso": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nicolás Lombaerts": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nicolò Zaniolo": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nigel Reo-Coker": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nigel de Jong": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nils Liedholm": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nuri Şahin": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Nwankwo Kanu": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Ove Kindvall": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Pablo Ibáñez": "a 35. köteg (3.9.117)",
  "Pablo Zabaleta": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Paolo Di Canio": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Park Ji-sung": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Patrick Kluivert": "a felhasználó kérése (2026-10-06)",
  "Patrik Schick": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Pavel Srníček": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Pedro": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Pedro Porro": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Per Mertesacker": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Phil Foden": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Philippe Coutinho": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Piero Hincapié": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Pietro Anastasi": "a 35. köteg (3.9.117)",
  "Presnel Kimpembe": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Radja Nainggolan": "a 33. köteg (3.9.114)",
  "Rafael van der Vaart": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Raheem Sterling": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Renato Sanches": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ricardo Quaresma": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Ricardo Sá Pinto": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Riccardo Ferri": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Rick Karsdorp": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Rob Witschge": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Robert Pirès": "a felhasználó kérése (2026-10-06)",
  "Rodrigo De Paul": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Rodrygo": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Roger Ibañez": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Roman Bürki": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Roman Weidenfeller": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Ronald Araújo": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Ronald Spelbos": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Roque Júnior": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Roy Makaay": "a 35. köteg (3.9.117)",
  "Ryan Gravenberch": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Sami Hyypiä": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Samir Handanović": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Samuel Umtiti": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Sebastian Giovinco": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Sebastian Kehl": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Shaun Wright-Phillips": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Simon Kjær": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Simon Mignolet": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Simone Inzaghi": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Sonny Silooy": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Stan Mortensen": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Stanley Matthews": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Stanley Menzo": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Stefan Reuter": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Stefan de Vrij": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Steffen Freund": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Steve Bruce Jr.": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Steve Finnan": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Stuart Pearce": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Sulley Muntari": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Sylvinho": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Sérgio Conceição": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Sérgio Oliveira": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Tammy Abraham": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Teddy Sheringham": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Teun Koopmeiners": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Theo Hernández": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Theodoros Zagorakis": "a 35. köteg (3.9.117)",
  "Thomas Delaney": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Thomas Hitzlsperger": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Thomas Häßler": "a 35. köteg (3.9.117)",
  "Thorgan Hazard": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Tomáš Rosický": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Tony Adams": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Torbjörn Nilsson": "a 35. köteg (3.9.117)",
  "Ubaldo Fillol": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Vincent Candela": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Vincent Kompany": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Vladimir Jugović": "a 36. köteg (3.9.119)",
  "Vladimír Šmicer": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Vágner Love": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Warren Zaïre-Emery": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Wesley Sneijder": "a felhasználó kérése (2026-10-06)",
  "William Gallas": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Willian": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Willy Sagnol": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Wolfgang Overath": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Xherdan Shaqiri": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Yaya Touré": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Yohan Cabaye": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Yuri Lodygin": "a 29–32. köteg danisítása (3.9.81–3.9.84)",
  "Ze Roberto": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
  "Álvaro Morata": "a 3.9.87-es kör (a kért gépi-név felülírások)",
  "Édmilson": "bf84bde — Nevek Danisítása lvl100 (2026-09-01)",
}

SAJAT = {
  "Aaron Lennon": ("Lenyó Áron", "Lenyó"),
  "Adamo Coulibaly": ("Kúlibali Ádám", "Kúlibali"),
  "Ademola Lookman": ("Figyeljmán Ademóla", "Figyeljmán"),
  "Adriano": ("Ádrijánó", "Ádrijánó"),
  "Adrien Rabiot": ("Rábijó Adriján", "Rábijó"),
  "Adrián": ("Ádriján", "Ádriján"),
  "Adílson": ("Ádílszon", "Ádílszon"),
  "Alan Shearer": ("Sír E. A. Lány", "Sírealány"),
  "Alberto Gilardino": ("Zsilárdínó Albert", "Zsilárdínó"),
  "Alberto Moreno": ("Morénó Albert", "Morénó"),
  "Aleksandr Anyukov": ("Anyukád Tas", "Anyukád"),
  "Alessandro Bastoni": ("Bástonyi Sándor", "Bástonyi"),
  "Alessandro Birindelli": ("Birindelji Sándor", "Birindelji"),
  "Alessandro Costacurta": ("Aztakurva Sándor", "Aztakurva"),
  "Alessandro Nesta": ("Nesztea Sándor", "Nesztea"),
  "Alessio Romagnoli": ("Románjoli Miksa", "Románjoli"),
  "Alessio Tacchinardi": ("Tacskónárdi Elek", "Tacskónárdi"),
  "Alex McLeish": ("Meklís Sanyi", "Meklís"),
  "Alex Oxlade-Chamberlain": ("Okszi-Csamberléjn Sándor", "Okszi-Csamberléjn"),
  "Alexander Isak": ("Izsák Alex", "Izsák"),
  "Alexander Sørloth": ("Szőrló Sándor", "Szőrló"),
  "Alexandre Lacazette": ("Lakazetta Sándor", "Lakazetta"),
  "Alexis Mac Allister": ("Makelliszter Sándor", "Makelliszter"),
  "Alexis Saelemaekers": ("Szálkészítő Alex", "Szálkészítő"),
  "Alexis Sánchez": ("Sáncsesző Zalán", "Sáncsesző"),
  "Alfredo Di Stéfano": ("Disztefános Alfréd", "Distefános"),
  "Alisson Becker": ("Aluszékony Bekker", "Aluszékony"),
  "Altay Bayındır": ("Baj-Andi Altaj", "Baj-Andi"),
  "Amir Hadžiahmetović": ("Hadzsiahmetovics Salamon", "Hadzsiahmetovics"),
  "Andrea Pirlo": ("Piruló Andi", "Piruló"),
  "Andrea Ranocchia": ("Rántotta András", "Rántotta"),
  "Andreas Isaksson": ("Iszaksszon András", "Iszaksszon"),
  "Andrei Arshavin": ("Seggborotváló András", "Seggborotváló"),
  "Andrij Sevcsenko": ("Sebcselló Andris", "Sebcselló"),
  "Andriy Lunin": ("Lúnyin András", "Lúnyin"),
  "André Schürrle": ("Csürhe András", "Csürhe"),
  "André-Pierre Gignac": ("Zsinyak András", "Zsinyak"),
  "Andrés Iniesta": ("Ínyenc Pista Bandi", "Ínyenc Pista"),
  "Antoni Ramallets": ("Rámajetsz Tóni", "Rámajetsz"),
  "Antonio Cabrini": ("Kabrió Antal", "Kabrió"),
  "Antonio Di Natale": ("Dínótál E. Antal", "Dínótál"),
  "Artem Dzyuba": ("Dzsuba Zsigmond", "Dzsuba"),
  "Ashley Young": ("ifj. Fiatal Áron", "ifj. Fiatal"),
  "Aurélien Tchouaméni": ("Csúaméni Lehel", "Csúaméni"),
  "Axel Witsel": ("Viccel A. Xszel", "Viccel"),
  "Batista": ("Bátiszta", "Bátiszta"),
  "Batistuta": ("ifj. Bátyuska", "ifj. Bátyuska"),
  "Bebeto": ("Baba-tó", "Baba-tó"),
  "Beckenbauer": ("ifj. Bekembójer", "ifj. Bekembójer"),
  "Benjamin Pavard": ("Paraván Benjámin", "Paraván"),
  "Bergkamp": ("ifj. Bergkempingi", "ifj. Bergkempingi"),
  "Bernd Hölzenbein": ("Hölszenbájn Bernát", "Hölszenbájn"),
  "Bernd Schneider": ("Snájder Bernát", "Snájder"),
  "Blaise Matuidi": ("Matyódíszes Blézer", "Matyódíszes"),
  "Branislav Ivanović": ("Iványi Branyiszló", "Iványi"),
  "Brian Laudrup": ("Laudanum Brián", "Laudanum"),
  "Bruno Fernandes": ("Brunyáló Ferkó", "Burnyáló"),
  "Bruno Guimarães": ("Gumimaci Brunó", "Gumimaci"),
  "Bryan Cristante": ("Kristály Brájen", "Kristály"),
  "Cantona": ("ifj. Kántornak Tanult", "ifj. Kántornak"),
  "Casemiro": ("Kázijó Mirejó", "Kázijó"),
  "Charles De Ketelaere": ("Detekeláre Károly", "Detekeláre"),
  "Chris Armstrong": ("Erőskarú Krisztián", "Erőskarú"),
  "Chris Smalling": ("Kicsiző Krisztián", "Kicsiző"),
  "Chris Woods": ("Vúdsz Krisztián", "Vúdsz"),
  "Christian Abbiati": ("Albi Átiratás Krisztián", "Albi Átiratás"),
  "Christian Fuchs": ("Fuxos Krisztián", "Fuxos"),
  "Christian Karembeu": ("Karambol Krisztián", "Karambol"),
  "Christian Schulz": ("Sulc Krisztián", "Sulc"),
  "Ciro Immobile": ("Immozdulatlan Síró", "Immozdulatlan"),
  "Claudio Marchisio": ("Markízió Kálmán", "Markízió"),
  "Claudio Pizarro": ("Pizzaszaró Lehel", "Pizzaszaró"),
  "Clint Dempsey": ("Dempszi Benedek", "Dempszi"),
  "Cody Gakpo": ("Hákpó Vilmos", "Hákpó"),
  "Coen Moulijn": ("Múlejn Kohén", "Múlejn"),
  "Colin Calderwood": ("Kaldervúd Kóli", "Kaldervúd"),
  "Corentin Tolisso": ("Tolató Kornél", "Tolató"),
  "Costinha": ("Kosztinnya", "Kosztinnya"),
  "Cruyff": ("ifj. Krojfi", "ifj. Krojfi"),
  "Dani Olmo": ("Omlós Dani", "Omlós"),
  "Daniel Agger": ("Egér Dániel", "Egér"),
  "Daniel Carvalho": ("Karvaly Jó Dániel", "Karvaly Jó"),
  "Daniel Passarella": ("Faszerella Dániel", "Faszerella"),
  "Daniel Sturridge": ("Sztáridzs Dániel", "Sztáridzs"),
  "Daniel Van Buyten": ("Fanböjten Dániel", "Fanböjten"),
  "Daniele De Rossi": ("Derosszígy Dani", "Derosszígy"),
  "Danijel Subašić": ("Subások Dániel", "Subások"),
  "Danilo D'Ambrosio": ("Dámbrosio Dani", "Dámbrosio"),
  "Danilo": ("Dani a Ló", "DaniLó"),
  "Danny Rose": ("Rózsa Mór", "Rózsa"),
  "Danny": ("Danika", "Danika"),
  "Darren Anderton": ("Másiktonhal Dorián", "Másiktonhal"),
  "Darwin Núñez": ("Nyúnyez Kelemen", "Nyúnyez"),
  "David Beckham": ("Bekem Dávid", "Bekem"),
  "David Ginola": ("Zsinórka Dávid", "Zsinórka"),
  "David Ospina": ("Osztmivan Dávid", "Osztmivan"),
  "David Seaman": ("Tengerember Dávid", "Tengerember"),
  "Davide Zappacosta": ("Cappakoszta Jenő", "Cappakoszta"),
  "Dayot Upamecano": ("Uppáré Dejó", "Uppáré"),
  "Declan Rice": ("Rizsecske Dékán", "Rizsecske"),
  "Deco": ("Dekázó", "Dekázó"),
  "Dejan Kulusevski": ("Kuluszevszki Ábel", "Kuluszevszki"),
  "Dejan Stanković": ("Sztankovics Deján", "Sztankovics"),
  "Denílson": ("Denifia", "Denifia"),
  "Derlei": ("Der Lej", "Der Lej"),
  "Di Stéfano": ("ifj. Disztefános", "ifj. Disztefános"),
  "Didi": ("Csöcs", "Csöcs"),
  "Diego Forlán": ("Fórlány Rezső", "Fórlány"),
  "Diego Milito": ("Miliméteres Dijégó", "Miliméteres"),
  "Diego Tristán": ("Trísztán Ábris", "Trísztán"),
  "Diego": ("Dijégó", "Dijégó"),
  "Diogo Jota": ("Zsóta Dijégó", "Zsóta"),
  "Dirk Kuyt": ("Köjt Barnabás", "Köjt"),
  "Divock Origi": ("Óriginál Vazul", "Óriginál"),
  "Djibril Cissé": ("Sziszegő Dzsibrill", "Sziszegő"),
  "Djimi Traoré": ("Trajoré Jim", "Trajoré"),
  "Dombi Tibor": ("Bombázó Tibi", "Bombázó"),
  "Domenico Criscito": ("Krisszító Domonkos", "Krisszító"),
  "Dominic Calvert-Lewin": ("Kárérte-Levinek Lehel", "Kárérte-Levinek"),
  "Douglas Costa": ("Dugulást Okozta", "Dugulást Okozta"),
  "Dragan Stojković": ("Sztojkovics Pongrác", "Sztojkovics"),
  "Dries Mertens": ("Mertensz Megszárít", "Mertensz"),
  "Dwight Yorke": ("Dwáj Tyork", "Dwáj Tyork"),
  "Ederson": ("Éderfia", "Éderfia"),
  "Eduardo Camavinga": ("Kámávinga Ede", "Kámávinga"),
  "Edílson": ("Édílfia", "Édílfia"),
  "Eliseu": ("Elizeus", "Elizeus"),
  "Emil Forsberg": ("Fórszberg Emil", "Fórszberg"),
  "Emmanuel Adebayor": ("Ajjdebajos Manó", "Ajjdebajos"),
  "Emmanuel Ntim": ("Egycsapat Manó", "Egycsapat"),
  "Emmanuel Petit": ("Pici Manó", "Pici"),
  "Emre Can": ("Kan Imre", "Kan"),
  "Enrico Chiesa": ("Kieza Tihamér", "Kieza"),
  "Eric Cantona": ("Kántornak Tanult", "Kántornak"),
  "Eric Dier": ("Dajjer Erik", "Dajjer"),
  "Eric Maxim Choupo-Moting": ("Csupa-Mócsing Erik", "Csupa-Mócsing"),
  "Erling Haaland": ("Hólánc Erik", "Hólánc"),
  "Erwin Koeman": ("Kúman Farkas", "Kúman"),
  "Estanislau Basora": ("Básora Szabolcs", "Básora"),
  "Esteban Cambiasso": ("Kampikasszó Pista", "Kampikasszó"),
  "Everton": ("Mindigton", "Mindigton"),
  "Ezequiel Garay": ("Garai Ezékiel", "Garai"),
  "Ezequiel Lavezzi": ("Lávedzi Benedek", "Lávedzi"),
  "Fabio Grosso": ("Grosszó Máté", "Grosszó"),
  "Fabrizio Miccoli": ("Mikori Rezső", "Mikori"),
  "Falcão": ("Falkajó", "Falkajó"),
  "Federico Bernardeschi": ("Bernát Ezki Vilmos", "Bernát Ezki"),
  "Federico Chiesa": ("Kieza Dezső", "Kieza Dezső"),
  "Federico Valverde": ("Vállvetve Frigyes", "Vállvetve"),
  "Fernando Couto": ("Kutyó Nándor", "Kutyó"),
  "Filippo Inzaghi": ("Indzagi Fülöp", "Indzagi"),
  "Florian Wirtz": ("Virc Flóri", "Virc"),
  "Flávio Conceição": ("Konszészáó Boldizsár", "Konszészáó"),
  "Franco Mastantuono": ("Masztántónó Ferenc", "Masztántónó"),
  "Frank Anguissa": ("Angyiska Ferenc", "Angyiska"),
  "Frank de Boer": ("Debóra Ferenc", "Debóra"),
  "Freddie Ljungberg": ("Júnber Zétény", "Júnber"),
  "Gabi": ("Gabika", "Gabika"),
  "Gabriel Batistuta": ("Bátyuska Gábor", "Bátyuska"),
  "Gabriel Heinze": ("Henceg Gábor", "Henceg"),
  "Gabriel Jesus": ("Jézus Gábor", "Jézus G."),
  "Gabriel Milito": ("Milító Gábor", "Milító"),
  "Gareth Barry": ("Barika Geret", "Barika"),
  "Gareth Southgate": ("Délikapu Geret", "Délikapu"),
  "Gavi": ("Gagyi", "Gagyi"),
  "Georg Schwarzenbeck": ("Svarcol-Bekk György", "Svarcol-Bekk"),
  "Georgi Kinkladze": ("Kintyalaza Ákos", "Kintyalaza"),
  "Gianluca Pagliuca": ("Pali Lyuka Lukács", "Pali Lyuka"),
  "Gift Orban": ("Orrban az Ajándék", "Órban"),
  "Gilberto Silva": ("Zsilbertó Szilva", "Zs. Szilva"),
  "Giorgi Mamardashvili": ("Mamár-Dasvili György", "Mamár-Dasvili"),
  "Giovanni Reyna": ("Rejna János", "Rejna"),
  "Giuseppe Signori": ("Sinyóri József", "Sinyóri"),
  "Gonzalo Higuaín": ("Higany Jenő", "Higany"),
  "Granit Xhaka": ("Csaka Dezső", "Kskhaka"),
  "Grosics Gyula": ("Gyorsíccs Gyuszika", "Gyorsíccs"),
  "Grégory Coupet": ("Q. P. Gergely", "Q. P."),
  "Gullit": ("Zsüli", "Zsüli"),
  "Gulácsi Péter": ("Gula Peti", "Gula"),
  "Gunnar Gren": ("Ződ Gúnár", "Ződ"),
  "Gunnar Nordahl": ("Nórdal Gúnár", "Nórdal"),
  "Gustau Biosca": ("Blocska Gusztáv", "Blocska"),
  "Guti": ("Hutyi", "Hutyi"),
  "Hakim Ziyech": ("Zijes Vazul", "Zijes"),
  "Hans-Georg Schwarzenbeck": ("Svarcenbekk János-György", "Svarcenbekk"),
  "Harald Schumacher": ("Sumákoló Herold", "Sumákoló"),
  "Harry Kewell": ("Kjúúl Bálint", "Kjúúl"),
  "Helton": ("Eltony", "Eltony"),
  "Henrikh Mkhitaryan": ("Mikitalján Henrik", "Mikitalján"),
  "Hernán Crespo": ("Kreszpó Ernő", "Kreszpó"),
  "Hiroki Ito": ("Ító Dezső", "Ító"),
  "Hugo Ekitiké": ("Etyityike Hugó", "Etyityike"),
  "Hugo Lloris": ("Jórizs Hugó", "Jórizs"),
  "Hugo Viana": ("Vájáná Hugó", "Vájáná"),
  "Hulk": ("Hulkakolbász", "Hulkakolbász"),
  "Hélder Postiga": ("Postacsiga Jenő", "Postacsiga"),
  "Ian Ferguson": ("Férguszon Pongrác", "Férguszon"),
  "Ian Walker": ("Gyalogos Ájen", "Gyalogos"),
  "Ibrahim Afellay": ("Afelár Gellért", "Afelár"),
  "Ibrahim Cissé": ("Cici Szabolcs", "Cici"),
  "Ibrahima Konaté": ("Kannaté Pongrác", "Kannaté"),
  "Ibrahima Sissoko": ("Sisszokkó Bertalan", "Sisszokkó"),
  "Idrissa Gueye": ("Géj Rezső", "Géj"),
  "Igor Bogdanović": ("Bogdán Ovis Igor", "Bogdán Ovis"),
  "Ivan Rakitić": ("Rakétácska Iván", "Rakétácska"),
  "Iván Córdoba": ("Kordbársony Iván", "Kordbársony"),
  "Jack Grealish": ("Girhes Jakab", "Girhes"),
  "Jadon Sancho": ("Száncsók Dzsédön", "Száncsók"),
  "James Milner": ("Malmos Jakab", "Malmos"),
  "Jamie Vardy": ("Váradi Dzsémi", "Váradi Dzsé."),
  "Jan Koller": ("Kollár János", "Kollár"),
  "Jan Oblak": ("Ablak János", "Ablak"),
  "Jan Wouters": ("Vúters János", "Vúters"),
  "Jefferson Farfán": ("Farafán Zsigmond", "Farafán"),
  "Jemerson": ("Dzsémerson", "Dzsémerson"),
  "Jeremie Frimpong": ("Frimpingpong Domonkos", "Frimpingpong"),
  "Jermain Defoe": ("Defó Boldizsár", "Defó"),
  "Jerzy Dudek": ("Dudika Dzserzi", "Dudika"),
  "Jesús Fernández": ("Fernándessz Jézus", "Jézus F."),
  "Jesús Gámez": ("Gámessz Jézus", "Jézus Gám."),
  "Jesús Navas": ("Navász Jézus", "Jézus N."),
  "Joan Segarra": ("Szegárá Jóvan", "Szegárá"),
  "Joe Gomez": ("Gombos Jocó", "Gombos"),
  "Joe Hart": ("Szív Dzsó", "Szív"),
  "John Arne Riise": ("Ríííze János", "Ríííze"),
  "John Bosman": ("Főnökember János", "Főnökember"),
  "John Obi Mikel": ("Mikell Obiból János", "Mikell Obiból"),
  "John van 't Schip": ("Fan'csip János", "Fan'csip"),
  "Joleon Lescott": ("Leszokott Dzsóleon", "Leszokott"),
  "Jordan Pickford": ("Pikkforduló Gellért", "Pikkforduló"),
  "Jordi Cruyff": ("Krojfi Ernő", "Krojfi E."),
  "Jorginho": ("Zsordzsinnyó", "Zsordzsinnyó"),
  "Josemi": ("Józsimi", "Józsimi"),
  "José Callejón": ("Kaljehón József", "Kaljehón"),
  "José Fonte": ("Fontoskodó József", "Fontoskodó"),
  "João Manuel Pinto": ("Pin-Tó János", "Pin-Tó"),
  "João Neves": ("Nevezetes János", "Nevezetes"),
  "Juan Cuadrado": ("Kuadrádo János", "Kuadrádo"),
  "Julian Brandt": ("Pálinkás Gyula", "Pálinkás"),
  "Julian Draxler": ("Drakszler Gyula", "Drakszler"),
  "Jérémy Mathieu": ("Matyóka Jeremiás", "Matyóka"),
  "Jürgen Grabowski": ("Ternovszki György", "Ternovszki"),
  "Kai Havertz": ("Haver Káj", "Haverkáj"),
  "Kalidou Koulibaly": ("Kúlibali Kalidú", "Kúlibali"),
  "Kamil Glik": ("Glükóz Kamill", "Glükóz"),
  "Kasper Schmeichel": ("Smájkell Kászper", "Smájkell"),
  "Kerkez Milos": ("Kér Kéz Milliós", "Kér Kéz"),
  "Khalid Boulahrouz": ("Búlahrúz Bertalan", "Búlahrúz"),
  "Kim Jin-su": ("Kím Ernő", "Kím"),
  "Kim Min-jae": ("Kím Miksa", "Kím"),
  "Kingsley Coman": ("Királyi Komám", "Királyi"),
  "Kolo Touré": ("Túré Kolos", "Túré"),
  "Kostas Manolas": ("Mandolás Kostás", "Mandolás"),
  "Kostas Tsimikas": ("Cimikás Konstantin", "Cimikás"),
  "Kubala László": ("Q-Balla Lackó", "Q-Balla"),
  "Kwoun Sun-tae": ("Kvún Kelemen", "Kvún"),
  "Kylian Mbappé": ("Kilján Bapé", "Bapé"),
  "Leandro Paredes": ("Párezres Pongrác", "Párezres"),
  "Leandro Trossard": ("Trosszár Benedek", "Trosszár"),
  "Lee Kang-in": ("Lí Ernő", "Lí"),
  "Leon Goretzka": ("Gorecka Lénárd", "Gorecka"),
  "Leonardo Spinazzola": ("Szpínazólá Lénárd", "Szpínazólá"),
  "Lionel Scaloni": ("Skálázó Leó", "Skálázó"),
  "Lisandro Martínez": ("Lisztanyó Marcinyó", "Lisztanyó Marcinyó"),
  "Lorenzo Insigne": ("Inszinye Lőrinc", "Inszinye"),
  "Lorenzo Pellegrini": ("Pellengér Lőrinc", "Pellengér"),
  "Lucas Hernández": ("Hernánt Tesz Lukács", "Hernánt Tesz L."),
  "Luka Jović": ("Jovics Lukács", "Jovics"),
  "Lukas Podolski": ("Pokolszki Lukács", "Pokolszki"),
  "Manuel Akanji": ("Ákándzsi Manó", "Ákándzsi"),
  "Manuel Locatelli": ("Lyukateli Manó", "Lyukateli"),
  "Marc Cucurella": ("Kukurellya Márk", "Kukurellya"),
  "Marc Overmars": ("Óvermarsz Márk", "Óvermarsz"),
  "Marc-André ter Stegen": ("Ferstéhen Márk", "Ferstéhen"),
  "Marcel Tisserand": ("Tisszerán Marcell", "Tisszerán"),
  "Marcelo Salas": ("Szálas Marcell", "Szálas"),
  "Marco Asensio": ("Aszenszijjó Márk", "Aszenszijjó"),
  "Marco Materazzi": ("Anyarazzia Márkó", "Anyarazzia"),
  "Marco Reus": ("Rojsz Márk", "Rojsz"),
  "Marcos Senna": ("Széna Márk", "Széna M."),
  "Marek Hamšík": ("Hám Sík Márk", "Hám Sík"),
  "Mario Balotelli": ("Balhételi Márió", "Balhételi"),
  "Mario Corso": ("Korzózó Márijó", "Korzózó"),
  "Mario Kempes": ("Kemence Márió", "Kemence"),
  "Mark Hughes": ("Hiúz Márk", "Hiúz"),
  "Mark Iuliano": ("Júlianő Márk", "Júlianő"),
  "Mark van Bommel": ("Fánbomlikel Márk", "Fánbomlikel"),
  "Martin Peters": ("Pítörsz Márton", "Pítörsz"),
  "Martin Škrtel": ("Skrőte Márton", "Skrőte"),
  "Martín Demichelis": ("Demikellisz Márton", "Demikellisz"),
  "Mathieu Debuchy": ("Debuzi Máté", "Debuzi"),
  "Mauro Camoranesi": ("Kamoranézi Gyárfás", "Kamoranézi"),
  "Micah Richards": ("Ricsardsz Miká", "Ricsardsz"),
  "Michael Owen": ("Májkell Óven", "Óven"),
  "Milan Baroš": ("Balos Milán", "Balos"),
  "Milan Škriniar": ("Skrinyár Milán", "Skrinyár"),
  "Mimis Domazos": ("Dómazos Mimi", "Dómazos"),
  "Moisés Caicedo": ("Kájszédó Gyárfás", "Kájszédó"),
  "Mário Jardel": ("Járd El Márió", "Járd El"),
  "Nani": ("Nyanyi", "Nyanyi"),
  "Nathan Aké": ("Oké Vajk", "Oké"),
  "Nazım Sangaré": ("Szanga-Ré Nacika", "Szanga-Ré"),
  "Neven Subotić": ("Szubotics Nesztor", "Szubotics"),
  "Nicola Amoruso": ("Ámorűző Miklós", "Ámorűző"),
  "Nicolás Lombaerts": ("Lombba-Erc Niki", "Lombba-Erc"),
  "Nicolò Zaniolo": ("Zanyóló Nick", "Zanyóló"),
  "Nigel Reo-Coker": ("Rejó-Kokker Nájdzsel", "Rejó-Kokker"),
  "Nigel de Jong": ("Déjó N. G. Nájdzsel", "Déjó"),
  "Nils Liedholm": ("Lidérces Miklós", "Lidérces"),
  "Nuri Şahin": ("Sanyin Núri", "Sanyin"),
  "Nwankwo Kanu": ("Kenu Van Q", "Kenu"),
  "Ove Kindvall": ("Kindvál Óve", "Kindvál"),
  "Pablo Ibáñez": ("Ibán Yessz Pál", "Ibán Yessz"),
  "Pablo Zabaleta": ("Zabál E. Tán Pabló", "Zabál E. Tán"),
  "Paolo Di Canio": ("Dikánya Pál", "Dikánya"),
  "Park Ji-sung": ("Párk Pongrác", "Párk"),
  "Patrick Kluivert": ("Klájvert Patrik", "Klájvert"),
  "Patrik Schick": ("Sikk Patrik", "Sikk"),
  "Pavel Srníček": ("Szrnícsek Pál", "Szrnícsek"),
  "Pedro Porro": ("Pornó Péter", "Pornó"),
  "Pedro": ("Pedro Amigo Mio", "Pedro Amigo Mio"),
  "Per Mertesacker": ("Méretreszakker Szabolcs", "Méretreszakker"),
  "Phil Foden": ("Fóden Filó", "Fóden"),
  "Philippe Coutinho": ("Kutinnyó Fülöp", "Kutinnyó"),
  "Piero Hincapié": ("Hinkanapé Bertalan", "Hinkanapé"),
  "Pietro Anastasi": ("Ananász Tázi Péter", "Ananász Tázi"),
  "Presnel Kimpembe": ("Kimenne Álmos", "Kimenne"),
  "Radja Nainggolan": ("Ragyás Nyálgollam", "Ragyás Nyálgollam"),
  "Rafael van der Vaart": ("Fanderfing Rafael", "Fanderfing"),
  "Raheem Sterling": ("Sztőr Link Dezső", "Sztőr Link"),
  "Renato Sanches": ("Sancsesz Rezső", "Sancsesz R."),
  "Ricardo Quaresma": ("Kvarezsma Rikárd", "Kvarezsma"),
  "Ricardo Sá Pinto": ("Pin-Tó SzaRikárd", "Pin-Tó"),
  "Riccardo Ferri": ("Feri Rikárd", "Feri"),
  "Rick Karsdorp": ("Kardos Richárd", "Kardos"),
  "Rob Witschge": ("Vicsge Robi", "Vicsge"),
  "Robert Pirès": ("Pirézs Robi", "Pirézs"),
  "Rodrigo De Paul": ("Dészarul Aurél", "Dészarul"),
  "Rodrygo": ("RodríGÓ", "RodríGÓ"),
  "Roger Ibañez": ("Ibányez Rodzser", "Ibányez"),
  "Roman Bürki": ("Bürkí Román", "Bürkí"),
  "Roman Weidenfeller": ("Vájdenfeller Román", "Vájdenfeller"),
  "Ronald Araújo": ("Áráúzsó Ronáld", "Áráúzsó"),
  "Ronald Spelbos": ("Spélbos Ronáld", "Spélbos"),
  "Roque Júnior": ("ifj. Rokve", "ifj. Rokve"),
  "Roy Makaay": ("Makáj Roj", "Makáj"),
  "Ryan Gravenberch": ("Hráfenberh Ábris", "Hráfenberh"),
  "Sami Hyypiä": ("Hippija Samu", "Hippija"),
  "Samir Handanović": ("Handanovics Samu", "Handanovics"),
  "Samuel Umtiti": ("Bumm Titi Sámuel", "Bumm Titi"),
  "Sebastian Giovinco": ("Dzsovinkó Sebestyén", "Dzsovinkó"),
  "Sebastian Kehl": ("Kehely Sebestyén", "Kehely"),
  "Shaun Wright-Phillips": ("Vrájt-Filipszilonos János", "Vrájt-Filipszilonos"),
  "Simon Kjær": ("Ser Simon", "Ser"),
  "Simon Mignolet": ("Minyolé Simon", "Minyolé"),
  "Simone Inzaghi": ("Indzagi Simon", "Indzagi"),
  "Sonny Silooy": ("Silúi Soma", "Silúi"),
  "Stan Mortensen": ("Mórtensffy Jenő", "Mórtensffy"),
  "Stanley Matthews": ("Mettyúz Csongor", "Mettyúz"),
  "Stanley Menzo": ("Mendzó Levente", "Mendzó"),
  "Stefan Reuter": ("Rejtő István", "Rejtő"),
  "Stefan de Vrij": ("Dévrizs István", "Dévrizs"),
  "Steffen Freund": ("Barátkozó István", "Barátkozó"),
  "Steve Bruce Jr.": ("ifj. Brusz Pista", "ifj. Brusz"),
  "Steve Finnan": ("Finnyás Sztivi", "Finnyás"),
  "Stuart Pearce": ("Bírsz Sztyuárt", "Bírsz"),
  "Sulley Muntari": ("Munt-Aranyos Szüli", "Munt-Aranyos"),
  "Sylvinho": ("Szilvinjóska", "Szilvinjóska"),
  "Sérgio Conceição": ("Konszészáó Szergej", "Konszészáó Sz."),
  "Sérgio Oliveira": ("Oli-Vera Szerdzsó", "Oli-Vera"),
  "Tammy Abraham": ("Ábrándos Tomi", "Ábrándos"),
  "Teddy Sheringham": ("Sör-Innám Tivadar", "Sör-Innám"),
  "Teun Koopmeiners": ("Kúpásók Ince", "Kúpásók"),
  "Theo Hernández": ("Hernánt Tesz Tivadar", "Hernánt Tesz T."),
  "Theodoros Zagorakis": ("Zagyva Teó", "Zagyva"),
  "Thomas Delaney": ("Deláni Tamás", "Deláni"),
  "Thomas Hitzlsperger": ("Hiklispenger Tamás", "Hiklispenger"),
  "Thomas Häßler": ("Hesszler Tamás", "Hesszler"),
  "Thorgan Hazard": ("Házard Torgyán", "Házard"),
  "Tomáš Rosický": ("Rózsicki Tamás", "Rózsicki"),
  "Tony Adams": ("Ádamosi Tóni", "Ádamosi"),
  "Torbjörn Nilsson": ("Nílszffy Szabolcs", "Nílszffy"),
  "Ubaldo Fillol": ("Filioli Zsombor", "Filioli"),
  "Vincent Candela": ("Kandalló Vince", "Kandalló"),
  "Vincent Kompany": ("Koppány Vince", "Koppány"),
  "Vladimir Jugović": ("Jugovics Vladi", "Jugovics"),
  "Vladimír Šmicer": ("Szmájszer Vladi", "Szmájszer"),
  "Vágner Love": ("Szerelmes Vágner", "Szerelmes Vágner"),
  "Warren Zaïre-Emery": ("Zaj-Imre Mór", "Zaj-Imre"),
  "Wesley Sneijder": ("Veszi Snájder", "Snájder"),
  "William Gallas": ("Gallyas Vilmos", "Gallyas"),
  "Willian": ("Villám", "Villám"),
  "Willy Sagnol": ("Szanyol Vili", "Szanyol"),
  "Wolfgang Overath": ("Óvárosi Farkas", "Óvárosi"),
  "Xherdan Shaqiri": ("Zserdány Zsagiri", "Zserdány Zsagiri"),
  "Yaya Touré": ("Jaja Túr É.", "Túr É."),
  "Yohan Cabaye": ("Kabáj Tas", "Kabáj"),
  "Yuri Lodygin": ("Lódi-Dzsin Jurika", "Lódi-Dzsin"),
  "Ze Roberto": ("iZé Robi", "iZé"),
  "Álvaro Morata": ("Morotva Alvár", "Morotva"),
}

# A 19 DÖNTÉSRE VÁRÓ NÉV (2026-10-06, a projektgazda döntése): 13 visszaállt
# az eredeti alakjára (Bástonyi, Rámajetsz, Dámbrosio, Köjt, Indzagi, Milító,
# Kjúúl, Kreszpó, Skrinyár, Fóden, Makáj, Rózsicki, Szmájszer), 6 a javaslatkör
# alakján maradt (Sziszegő, Gumimaci, Múlejn, Szálas Marcell, Balhételi,
# Lidérces) — mind a 19 a SAJAT-ban, befagyasztva.
DONTESRE_VAR = {}
